import{a as w,S,i as p}from"./assets/vendor-da186403.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const n={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),formInput:document.querySelector(".form-input"),btn:document.querySelector(".button"),container:document.querySelector(".container"),loadMoreBtn:document.querySelector(".load-more-btn"),cssLoader:document.querySelector("#span-loader")};async function y(o,t){const e="https://pixabay.com/api/?key=42339224-5f1cb7b0c825234adabadbe9d",r={q:`${o}`,imageType:"photo",orientation:"horizontal",safeSearch:"true",page:t,per_page:15};return(await w.get(e,{params:r})).data}const M={captionsData:"alt",captionDelay:250};function B(o){const{largeImageURL:t,webformatURL:i,tags:s,likes:e,views:r,comments:a,downloads:v}=o;return`
  <li class="gallery-item">
    <a href="${t}">
      <img class="gallery-image" src="${i}" alt="${s}">
    </a>
    <div class="text">
      <p><b>Likes: </b>${e}</p>
      <p><b>Views: </b>${r}</p>
      <p><b>Comments: </b>${a}</p>
      <p><b>Downloads: </b>${v}</p>
    </div>
  </li>`}function P(o){return o.map(B).join("")}function h(o){const t=P(o);n.gallery.insertAdjacentHTML("beforeend",t),new S(".gallery a",M).refresh()}function g(){n.cssLoader.classList.add("loader")}function l(){n.cssLoader.classList.remove("loader")}function u(){n.loadMoreBtn.classList.add("hidden")}function $(){n.loadMoreBtn.classList.remove("hidden")}function m(o){p.error({position:"topRight",message:o})}function b(o){p.info({position:"topRight",message:o})}let d,c,f;async function q(o){if(o.preventDefault(),g(),n.gallery.innerHTML="",d=n.formInput.value.trim(),c=1,!d)return l(),u(),m("Form field must be filled in.");try{const t=await y(d,c);if(t.totalHits===0)return l(),u(),b("Nothing found.");f=Math.ceil(t.totalHits/15),h(t.hits)}catch(t){m(t),f=0,n.gallery.innerHTML=""}l(),L(),n.form.reset()}async function E(){g(),c+=1;const o=await y(d,c);h(o.hits),l(),L();const t=n.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function L(){c>=f?(u(),b("We are sorry, but you have reached the end of search results.")):$()}n.form.addEventListener("submit",q);n.loadMoreBtn.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
