import{a as S,S as M,i as y}from"./assets/vendor-da186403.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const n={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),formInput:document.querySelector(".form-input"),btn:document.querySelector(".button"),container:document.querySelector(".container"),loadMoreBtn:document.querySelector(".load-more-btn"),cssLoader:document.querySelector("#span-loader")};async function h(o,t){const e="https://pixabay.com/api/?key=42339224-5f1cb7b0c825234adabadbe9d",r={q:`${o}`,imageType:"photo",orientation:"horizontal",safeSearch:"true",page:t,per_page:15};return(await S.get(e,{params:r})).data}const B={captionsData:"alt",captionDelay:250};function P(o){const{largeImageURL:t,webformatURL:c,tags:a,likes:e,views:r,comments:i,downloads:w}=o;return`
  <li class="gallery-item">
    <a href="${t}">
      <img class="gallery-image" src="${c}" alt="${a}">
    </a>
    <div class="text">
      <p><b>Likes: </b>${e}</p>
      <p><b>Views: </b>${r}</p>
      <p><b>Comments: </b>${i}</p>
      <p><b>Downloads: </b>${w}</p>
    </div>
  </li>`}function $(o){return o.map(P).join("")}let l;function g(o){l&&l.destroy();const t=$(o);n.gallery.insertAdjacentHTML("beforeend",t),l=new M(".gallery a",B),l.refresh()}function b(){n.cssLoader.classList.add("loader")}function d(){n.cssLoader.classList.remove("loader")}function f(){n.loadMoreBtn.classList.add("hidden")}function q(){n.loadMoreBtn.classList.remove("hidden")}function p(o){y.error({position:"topRight",message:o})}function L(o){y.info({position:"topRight",message:o})}let u,s,m;async function E(o){if(o.preventDefault(),b(),n.gallery.innerHTML="",u=n.formInput.value.trim(),s=1,!u)return d(),f(),p("Form field must be filled in.");try{const t=await h(u,s);if(t.totalHits===0)return d(),f(),L("Nothing found.");m=Math.ceil(t.totalHits/15),g(t.hits)}catch(t){p(t),m=0,n.gallery.innerHTML=""}d(),v(),n.form.reset()}async function I(){b(),s+=1;const o=await h(u,s);g(o.hits),d(),v();const t=n.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function v(){s>=m?(f(),L("We are sorry, but you have reached the end of search results.")):q()}n.form.addEventListener("submit",E);n.loadMoreBtn.addEventListener("click",I);
//# sourceMappingURL=commonHelpers.js.map
